name: deepfake_detection
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch
    - torchvision
    - opencv-python
    - matplotlib
    - scikit-learn
    - numpy
    - facenet-pytorch
    - Pillow
